# context "catalogue"
# it "creates new line if doesn't exist"
# it "updates existing line if exists"
# it "can add a specific value"
# it "can subtract a specific value"
# it "can set an absolute value"
# it "can delete a line"

# context "checkout"
# it "can add a specific value"
# it "can subtract a specific value"
# it "can set an absolute value"
# it "can delete a line"